### ISSUE TITLE
Add option to selectively skip linting with reserved comment

### ISSUE THREAD

**Issue by kwvg** [rcjsuen/dockerfile-utils#106]
## Description

Currently, `dockerfile-utils` cannot account for syntax extensions introduced with BuildKit causing false-positive error reporting with the example given below...

```dockerfile
# syntax = edrevo/dockerfile-plus
FROM ubuntu:focal
INCLUDE+ example/Dockerfile
RUN echo "Hello World"
```

The second line causes `dockerfile-utils` to return `Unknown instruction: INCLUDE+dockerfile-utils(38)`

## Proposal

Introduce the ability to (similar to ShellCheck, for instance `# shellcheck disable=SC1083`) selectively disable linting errors (specific or otherwise) for a block of instructions

Something along the lines of the example given below would be neat!

```dockerfile
# syntax = edrevo/dockerfile-plus
FROM ubuntu:focal

# dockerfile-utils: ignore
INCLUDE+ example/Dockerfile

RUN echo "Hello World"
```

**Comment by muuvmuuv** [comment]
Mhmm, any help needed here?

**Comment by rcjsuen** [comment]
@kwvg @muuvmuuv The change to support `# dockerfile-utils: ignore` comments have been published and released to npm in today's 0.12.0 release. Perhaps you have already moved on to a different linting library but I thought I would let you know anyway.

Have a nice weekend!

**Comment by kwvg** [comment]
Thanks for the surprise! Opened this issue more than a year ago so I'm glad it's fixed!

Have a great weekend!

**Comment by rcjsuen** [comment]
> This enhancement is not working properly. The `# dockerfile-utils: ignore` line does nothing.

@DaftValac Sorry to hear that. Perhaps I have missed something. Could you please open a new issue and share your Dockerfile and a screenshot? Thanks!
