### ISSUE TITLE
Empty lines in HEREDOCs trigger a warning (empty continuation line)

### ISSUE THREAD

**Issue by wedi** [rcjsuen/dockerfile-utils#107]
**issue:**  The linter complains about empty lines in HEREDOCs.

> Empty continuation line dockerfile-utils(11)

Test:
```js
const utils = require('dockerfile-utils');
const problems = utils.validate('FROM alpine\nRUN <<eot\necho "foo"\n\necho "bar"\neot');
console.log(problems);
```
```
1
```

In addition, I have experienced that VS Code added backslashes on pressing enter to escape newlines in HEREDOCs but I cannot reproduce that right now. Maybe this has been fixed recently?

**praise:** 

In https://github.com/rcjsuen/dockerfile-utils/issues/97 you started supporting HEREDOCs from the very beginning and in https://github.com/rcjsuen/dockerfile-utils/issues/105 you promptly fixed formatting when I reported that over at https://github.com/microsoft/vscode-docker/issues/3327. Thank you!

This tool works secretly behind the scenes and provides a tremendous value for everyone handling Dockerfiles with VS Code. This is just great. Thank you!

**Comment by rcjsuen** [comment]
Hi @wedi, thanks for the bug report.

1. For the empty continuation lines warning, in Visual Studio Code you can try setting `"docker.languageserver.diagnostics.emptyContinuationLine"` to `"ignore"` as a workaround.
2. The language server does not insert characters when "enter" is pressed. At least...it shouldn't. :P There might be some autoformatting/auto-tabbing behaviour but I don't think it should "randomly" be adding a `\` character. If you do see it again please open an issue in the [microsoft/vscode-docker repository](https://github.com/microsoft/vscode-docker) and CC me there.
3. Thank you for your compliments and recognition of this little project! The project wouldn't be this far without people like you opening bugs though (as the company I work with does not use heredoc syntax for example) so I appreciate everyone out there letting me know about updates to the Dockerfile syntax and false positives and so on. :)

**Comment by wedi** [comment]
Thanks for the prompt reply!
1. Thanks for the hint but I'll leave it as is for now. I prefer having a non disruptive false positive warning to broken images. :)
2. I've just realised that this was not VS Code but a JetBrains IDE. They do not support the LSP which is a shame.
3. ❤️

**Comment by rcjsuen** [comment]
Blocked by https://github.com/rcjsuen/dockerfile-ast/issues/103.

**Comment by rcjsuen** [comment]
@wedi I have opened https://github.com/microsoft/vscode-docker/pull/3399 to ask the engineers at Microsoft to update the Visual Studio Code Docker extension with the new fixed version.

Thanks again for the bug report and have a great weekend!
