### ISSUE TITLE
Support heredocs in the formatter for COPY instructions

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-utils#111]
```Dockerfile
# syntax=docker/dockerfile:1
FROM alpine
COPY <<-EOT /test.txt
	hello
EOT
```
```JavaScript
const lib = require("dockerfile-utils");
const content = `# syntax=docker/dockerfile:1
FROM alpine
COPY <<-EOT /test.txt
	hello
EOT`;
const edits = lib.format(content);
console.log(edits.length);
```
```
1
```
We should update the formatter to consider heredocs in COPY instructions.

**Comment by hgl** [comment]
Thanks for the fix. Would it be possible for this change to trickle down to [dockerfile-language-server-nodejs](https://github.com/rcjsuen/dockerfile-language-server-nodejs)?

**Comment by rcjsuen** [comment]
> Thanks for the fix. Would it be possible for this change to trickle down to [dockerfile-language-server-nodejs](https://github.com/rcjsuen/dockerfile-language-server-nodejs)?

> when will be published now?very preciate

I have just released a new version of `dockerfile-language-server-nodejs` (0.10.0) today with this fix. Sorry for the long delay but I have been distracted with other things so I could not get a chance to get this out sooner.
