### ISSUE TITLE
unknown flag --parents

### ISSUE THREAD

**Issue by stevenh** [rcjsuen/dockerfile-utils#123]
Getting a error that `--parents` to COPY is an unknown command.
```
Unknown flag: parents dockerfile-utils(40)
```

This is new and is part of the master-labs tag as specified in our `Dockerfile` using:
```docker
# syntax=docker/dockerfile-upstream:master-labs
```

**Comment by rcjsuen** [comment]
@stevenh Thank you for the bug report. This has now been fixed.
