### ISSUE TITLE
Multiple ENTRYPOINT/CMD/HEALTHCHECK warnings invalid in the context of a multi-stage Dockerfile

### ISSUE THREAD

**Issue by hairyhenderson** [rcjsuen/dockerfile-utils#22]
https://github.com/rcjsuen/dockerfile-utils/blob/88d1abe36cf708081af92de48a21e9c81fb3e038/src/dockerValidator.ts#L153

When using a multi-stage Dockerfile, these warnings trigger, but shouldn't. I suppose a possible way to fix this would be to reset the counts when a `FROM` instruction is encountered...

**Comment by rcjsuen** [comment]
Thank you very much for your bug report, @hairyhenderson. We should fix this for `CMD`, `ENTRYPOINT`, and `HEALTHCHECK`.
```Dockerfile
FROM alpine
CMD ls
FROM alpine
CMD pwd
```
```
$ dockerfile-utils lint Dockerfile
Line: 2
CMD ls
^^^
Warning: There can only be one CMD instruction in a Dockerfile

Line: 4
CMD pwd
^^^
Warning: There can only be one CMD instruction in a Dockerfile
```
```Dockerfile
FROM alpine
ENTRYPOINT ls
FROM alpine
ENTRYPOINT pwd
```
```
$ dockerfile-utils lint Dockerfile
Line: 2
ENTRYPOINT ls
^^^^^^^^^^
Warning: There can only be one ENTRYPOINT instruction in a Dockerfile

Line: 4
ENTRYPOINT pwd
^^^^^^^^^^
Warning: There can only be one ENTRYPOINT instruction in a Dockerfile
```
```Dockerfile
FROM alpine
HEALTHCHECK CMD ls
FROM alpine
HEALTHCHECK CMD pwd
```
```
$ dockerfile-utils lint Dockerfile
Line: 2
HEALTHCHECK CMD ls
^^^^^^^^^^^
Warning: There can only be one HEALTHCHECK instruction in a Dockerfile

Line: 4
HEALTHCHECK CMD pwd
^^^^^^^^^^^
Warning: There can only be one HEALTHCHECK instruction in a Dockerfile
```

**Comment by rcjsuen** [comment]
Fixed by 06de6f9b7c83822af4ebb397a40ce064f398cc50 but I wrote the wrong issue number in the commit message. :(

**Comment by hairyhenderson** [comment]
Thanks @rcjsuen! That was fast 😂

**Comment by rcjsuen** [comment]
@hairyhenderson No problem, thank you for opening the bug report! Would you like me to publish a new version to npm?

**Comment by hairyhenderson** [comment]
@rcjsuen yes please - I mainly use this through VSCode, so maybe more downstream things need to be updated as well... No huge rush though :)

**Comment by rcjsuen** [comment]
@hairyhenderson Ah. Yeah, then it'll take a while. :P

I'd have to trickle this change to my own downstream projects in addition to getting the dependency updated in the vscode-docker extension. And then the Microsoft guys would have to also agree to publish a new version to the Visual Studio Marketplace. :O

You must have done quite some detective work to get this far down the dependency chain though. Most people just open a bug in the vscode-docker extension and call it a day. ;)

If you are using VS Code though, you can disable the validation by modifying your settings. Naturally, this has the side effect of disabling the correct validation warning where multiples of these instructions appear in the same build stage...
```JSON
{
    "docker.languageserver.diagnostics.instructionCmdMultiple": "ignore",
    "docker.languageserver.diagnostics.instructionEntrypointMultiple": "ignore",
    "docker.languageserver.diagnostics.instructionHealthcheckMultiple": "ignore"
}
```

**Comment by hairyhenderson** [comment]
woot! Thanks @rcjsuen 😀
