### ISSUE TITLE
COPY command destination can be an ARG, but is currently flagged as an error

### ISSUE THREAD

**Issue by grantwwu** [rcjsuen/dockerfile-utils#54]
`COPY a bunch of files ${DESTINATION_DIR}` is currently flagged with `When using COPY with more than one source file, the destination must be a directory and end with a / or a \`.

I think we ought to suppress the warning here.

**Comment by rcjsuen** [comment]
@grantwwu Thank you so much for your bug report! This should be fixed now and it will be included in the next release.
