### ISSUE TITLE
Accept bash syntax for variable non-nullness

### ISSUE THREAD

**Issue by vbence** [rcjsuen/dockerfile-utils#56]
The following Dockerfile gives an error

> failed to process "${SPARK_PACKAGE:?}": unsupported modifier (?)

```
FROM centos:centos7

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ENV SPARK_VERSION 2.4.0
ENV HADOOP_VERSION 2.7
ENV SPARK_PACKAGE spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}
RUN curl -sL --retry 3 \
    "https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=spark/spark-${SPARK_VERSION}/${SPARK_PACKAGE}.tgz" \
    | gunzip \
    | tar x -C /usr/ \
    && mkdir -p /opt/spark/python \
    && mv "/usr/${SPARK_PACKAGE}/jars" /opt/spark/jars \
    && mv "/usr/${SPARK_PACKAGE}/bin" /opt/spark/bin \
    && mv "/usr/${SPARK_PACKAGE}/sbin" /opt/spark/sbin \
    && mv "/usr/${SPARK_PACKAGE}/conf" /opt/spark/conf \
    && mv "/usr/${SPARK_PACKAGE}/examples" /opt/spark/examples \
    && mv "/usr/${SPARK_PACKAGE}/data" /opt/spark/data \
    && mv "/usr/${SPARK_PACKAGE}/kubernetes/tests" /opt/spark/tests \
    && mv "/usr/${SPARK_PACKAGE}/python/lib" /opt/spark/python/lib \
    && rm -rf "/usr/${SPARK_PACKAGE:?}"
```

The syntax is required by hadolint. Which otherwise gives:
> Dockerfile:8 SC2115 Use "${var:?}" to ensure this never expands to /usr .

**Comment by rcjsuen** [comment]
Hi, @vbence. Thank you for your bug report.

From a cursory glance, this seems to only work for `RUN` instructions. I tried using `?` in `WORKDIR` and `USER` and Docker didn't seem to like it. Does this assessment sound correct to you?

**Comment by vbence** [comment]
Hi,
Yes this use is shell-specific.
https://wiki.bash-hackers.org/syntax/pe

**Comment by rcjsuen** [comment]
@vbence Thank you for your information. I think I'll relax this check if it's used within a `RUN` instruction then.

**Comment by rcjsuen** [comment]
@vbence Thank you again for your bug report. The validator will now ignore the `?` modifier if it's found in a `RUN` instruction.

**Comment by vbence** [comment]
Thank you so much Remy, you run one of the most responsive projects I’be seen!
