### ISSUE TITLE
Using EXPOSE with ENV that refers to ARG does not work

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-utils#57]
It seems that having an `ENV` that points to an `ARG` and having `EXPOSE` use the `ENV` doesn't work.
```Dockerfile
FROM scratch
ARG ARG_VAR=1234
ENV ENV_VAR $ARG_VAR
EXPOSE "$ENV_VAR"
```
```
$ docker build .
Sending build context to Docker daemon  1.733MB
Step 1/4 : FROM scratch
 --->
Step 2/4 : ARG ARG_VAR=1234
 ---> Running in d11c3cbd301f
Removing intermediate container d11c3cbd301f
 ---> e0b65ca26989
Step 3/4 : ENV ENV_VAR $ARG_VAR
 ---> Running in 3cf0d510bfef
Removing intermediate container 3cf0d510bfef
 ---> 75bf7f395cea
Step 4/4 : EXPOSE "$ENV_VAR"
 ---> Running in ec6d2ec6dac6
Removing intermediate container ec6d2ec6dac6
 ---> 491e81f62d04
Successfully built 491e81f62d04
[node1] (local) root@192.168.0.13 ~
```

**Comment by rcjsuen** [comment]
Whoops, forgot to include the error we're getting.
```
$ dockerfile-utils lint Dockerfile
Line: 4
EXPOSE "$ENV_VAR"
       ^^^^^^^^^^
Error: Invalid containerPort: "$ARG_VAR
```

**Comment by nikhilgupta00008** [comment]
Just want to add more information We are setting ARG value from env and docker-compose.yml. 
env files value is 1235 . I am getting this error on windows docker toolbox.
![dockererror](https://user-images.githubusercontent.com/49809252/56457117-db2ccf00-6393-11e9-983b-03dc5d302b05.png)

**Comment by rcjsuen** [comment]
@nikhilgupta00008 That is an error generated by Docker itself and is not an error message generated by this project.

It seems like you should not use quotations in `EXPOSE`. Why are you using quotes in `EXPOSE` anyway?

**Comment by rcjsuen** [comment]
@nikhilgupta00008 Actually, I've just reviewed your comments again.

It seems to me that Docker Toolbox doesn't handle this case. You should raise this issue with the Docker folks if it is of importance to you.

**Comment by rcjsuen** [comment]
@nikhilgupta00008 Thank you again for your bug report. I've just released a fix for this to `master`.
