### ISSUE TITLE
Add formatting option for ignoring multiline statements

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-utils#62]
```Dockerfile
RUN apt-get update -y && \
    apt-get install -y curl && \
            git \
            make
```
For some instructions where the `RUN` has multiple "layers" like the above, users may not want it to be reformatted back to the following.
```Dockerfile
RUN apt-get update -y && \
    apt-get install -y curl && \
    git \
    make
```

**Comment by tagirb** [comment]
Hi @rcjsuen, thanks a lot for working on this project! Are there any plans on fixing this issue?

I don't know if it'd be easier to implement, but to me it looks even better if ampersands `&&` are moved to the next line:

```
RUN apt-get update -y \
    && apt-get install -y \
        git \
        make
```

So, essentially you just need to indent the lines not starting with `&& ` by one level.

**Comment by rcjsuen** [comment]
> Hi @rcjsuen, thanks a lot for working on this project! Are there any plans on fixing this issue?

@tagirb The desire is there but I haven't really acted on it due to https://github.com/microsoft/language-server-protocol/issues/567 which makes the experience of toggling this cumbersome for some LSP clients. I suppose I could always implement it and then improve on it later so that there's at least a temporary stopgap.

> I don't know if it'd be easier to implement, but to me it looks even better if ampersands `&&` are moved to the next line:
> 
> ```
> RUN apt-get update -y \
>     && apt-get install -y \
>         git \
>         make
> ```
> 
> So, essentially you just need to indent the lines not starting with `&& ` by one level.

This suggestion would probably work better as a separate enhancement request. Most shells work with `&&` but I believe PowerShell does not use that syntax.

**Comment by rcjsuen** [comment]
I know this has taken a long time to get addressed but clients can now ignore multiline instructions when calling the API. I've opened #88 to add a flag to the CLI to support this.

**Comment by diegocars** [comment]
@rcjsuen how do we ignore it?

**Comment by rcjsuen** [comment]
> @rcjsuen how do we ignore it? got here from this thread btw [microsoft/vscode-docker#2004](https://github.com/microsoft/vscode-docker/issues/2004)

@diegocars Thanks for reaching out and bringing this to my attention. This isn't possible in the extension at the moment but it can be with a fix. I'll take a look.

**Comment by rcjsuen** [comment]
@diegocars I've opened https://github.com/microsoft/vscode-docker/pull/2976 to enable support for this option in the VS Code extension.
