### ISSUE TITLE
CLI formatter always appends empty newline when printing to console

### ISSUE THREAD

**Issue by huonw** [rcjsuen/dockerfile-utils#63]
The format command is great for getting consistent indentation, but it unfortunately seems to add a newline to the end of the file, always:

```
$ docker pull rcjsuen/dockerfile-utils
...
$ docker run --rm -it -v $PWD:/mnt --entrypoint /bin/sh rcjsuen/dockerfile-utils
```

Inside the image:

Base "file":
```
/dockerfile-utils # echo 'FROM scratch'
FROM scratch
/dockerfile-utils # echo 'FROM scratch' | hexdump -C
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68 0a           |FROM scratch.|
0000000d
```
Formatting once:
```
/dockerfile-utils # echo 'FROM scratch' | bin/dockerfile-utils format /dev/stdin
FROM scratch

/dockerfile-utils # echo 'FROM scratch' | bin/dockerfile-utils format /dev/stdin | hexdump -C
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68 0a 0a        |FROM scratch..|
0000000e
```
Formatting twice:
```
/dockerfile-utils # echo 'FROM scratch' | bin/dockerfile-utils format /dev/stdin | bin/dockerfile-utils format /dev/stdin
FROM scratch


/dockerfile-utils # echo 'FROM scratch' | bin/dockerfile-utils format /dev/stdin | bin/dockerfile-utils format /dev/stdin | hexdump -C
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68 0a 0a 0a     |FROM scratch...|
0000000f
```

I've included the `hexdump` to be sure of the text that is being printed: `0a` is the hex ASCII value of `\n`.

**Comment by rcjsuen** [comment]
@huonw Thank you very much for your detailed steps. While I am able to reproduce this issue using `/dev/stdin` as you described, I am unable to reproduce this issue when I use just a one line Dockerfile with only `FROM scratch` and no trailing newline. Can you?

**Comment by huonw** [comment]
> I am unable to reproduce this issue when I use just a one line Dockerfile with only FROM scratch and no trailing newline

It still adds a newline in that case, which matches the description in the issue ("always adding a newline" goes from 0 `\n`s to 1 `\n`), although it is probably the only case when it is the correct behaviour.

```
/dockerfile-utils # echo -n 'FROM scratch' > Dockerfile
/dockerfile-utils # hexdump -C Dockerfile 
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68              |FROM scratch|
0000000c
/dockerfile-utils # bin/dockerfile-utils format Dockerfile 
FROM scratch
/dockerfile-utils # bin/dockerfile-utils format Dockerfile | hexdump -C
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68 0a           |FROM scratch.|
0000000d
```

Just to confirm, if there is a newline at the end of a file on disk (not just the `/dev/stdin` trick), `dockerfile-utils format` will still add an additional one, resulting in two (and similarly, if there's two trailing newlines, it will add another one resulting in three). Here's going from one to two:

```
/dockerfile-utils # echo 'FROM scratch' > Dockerfile
/dockerfile-utils # hexdump -C Dockerfile 
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68 0a           |FROM scratch.|
0000000d

/dockerfile-utils # bin/dockerfile-utils format Dockerfile 
FROM scratch

/dockerfile-utils # bin/dockerfile-utils format Dockerfile | hexdump -C
00000000  46 52 4f 4d 20 73 63 72  61 74 63 68 0a 0a        |FROM scratch..|
0000000e
```

**Comment by rcjsuen** [comment]
> > I am unable to reproduce this issue when I use just a one line Dockerfile with only FROM scratch and no trailing newline
> 
> It still adds a newline in that case, which matches the description in the issue ("always adding a newline" goes from 0 `\n`s to 1 `\n`)

@huonw I was aware of what you wrote in your original comment and in the description of the issue but I reached out to ask anyway because I was having difficulties reproducing the problem. 

I believe I understand the problem you are describing now that I've run through the scenarios a few more times. Thank you for the bug report and please accept my apologies for making you repeat yourself.

**Comment by huonw** [comment]
No problem at all. Thank you for the very quick replies! 👍

**Comment by rcjsuen** [comment]
@huonw Hi, Huon. Thank you once again for reporting this bug. The fix has been released and is now live.

Please pull `rcjsuen/dockerfile-utils` from Docker Hub again to grab the fix. You can use the `latest` or the `5732675fe799635ce81d187114c495da953706ff` tag.

Have a great week!
