### ISSUE TITLE
Unsupported modifier error may not be correct

### ISSUE THREAD

**Issue by tymokvo** [rcjsuen/dockerfile-utils#91]
Related to #38 , an error is issued for variable expansion of the form `ENV FOO=${FOO:?}`

```
failed to process "${SERVICE_NAME:?}": unsupported modifier (?) in substitution
```

However, this does not seem to be true as building a Dockerfile with this syntax works (as I, at least) expect. E.g. building this file:

```dockerfile
FROM ubuntu:20.04

ARG FOO

ENV FOO=${FOO:?}
```

...results in:

```
Step 3/3 : ENV FOO=${FOO:?}
failed to process "${FOO:?}": FOO: is not allowed to be unset
```

unless passed `--build-arg FOO=bar`.

`Docker version 20.10.5, build 55c4c88`

Let me know if I can provide any more info!

**Comment by rcjsuen** [comment]
@tymokvo I have reproduced the issue. Thank you for the bug report!

**Comment by rcjsuen** [comment]
@tymokvo The issue has now been fixed. Thanks again!

**Comment by tymokvo** [comment]
Wow, fast turnaround!
